name: Tenable WAS CI Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tenable-was-scan:
    name: Run Tenable WAS Docker CI/CD Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Docker network
        run: docker network create juice-shop-net

      - name: Start OWASP Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm \
            --name juice-shop \
            --network juice-shop-net \
            -p 3000:3000 \
            bkimminich/juice-shop

      - name: Wait for Juice Shop (internal check)
        run: |
          for i in {1..12}; do
            if docker run --rm --network juice-shop-net curlimages/curl:latest curl -s http://juice-shop:3000 > /dev/null; then
              echo "Juice Shop is reachable from Docker network";
              exit 0
            fi
            echo "Waiting for Juice Shop to be ready (internal)...";
            sleep 5
          done
          echo "Juice Shop failed to respond within timeout";
          exit 1

      - name: Run Tenable Web App Scanner
        run: |
          docker run --rm --network juice-shop-net curlimages/curl curl http://juice-shop:3000
          docker pull tenable/was-scanner:latest
          docker run \
            --rm \
            --network juice-shop-net \
            -e WAS_MODE=cicd \
            -e ACCESS_KEY=$ACCESS_KEY \
            -e SECRET_KEY=$SECRET_KEY \
            -e STARTUP_TIMEOUT=60 \
            -v ./:/scanner \
            tenable/was-scanner:latest
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Cleanup
        if: always()
        run: docker stop juice-shop || true
