name: CI WAS Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tenablescan:
    name: was-cicd
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Start network
        run: |
          docker network create juice-shop-net

      - name: Start Juice Shop (background)
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm \
            --name juice-shop \
            --network juice-shop-net \
            -p 3000:3000 \
            bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!";
              exit 0;
            fi
            echo "Waiting for Juice Shop...";
            sleep 5
          done
          echo "Juice Shop failed to start";
          exit 1

      - name: Run WAS
        run: |
          docker pull tenable/was-scanner:latest
          docker run \
            --network juice-shop-net \
            -e WAS_MODE=cicd \
            -e ACCESS_KEY=2f3865a71175c25b63c651d237b53e23ccfddba3ca0ff3e1d2b0de3fa0019bc0 \
            -e SECRET_KEY=8855e4186189cd3e15c95bc1f141e4264f34d7e2bb58b8d3aeda17a6eafa34e3 \
            -v ./:/scanner \
            tenable/was-scanner:latest
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Cleanup
        run: docker stop juice-shop || true
