name: Tenable WAS CI Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  tenable-was-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 1) Start Juice Shop on default bridge
      - name: Start OWASP Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm \
            --name juice-shop \
            -p 3000:3000 \
            bkimminich/juice-shop

      # 2) Wait for it to be reachable
      - name: Wait for Juice Shop
        run: |
          for i in {1..12}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              exit 0
            fi
            echo "Waiting for Juice Shop…"
            sleep 5
          done
          echo "Juice Shop failed to start in time."
          exit 1

      # 3) Run the scanner with --link
      - name: Run Tenable WAS Scanner
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker pull tenable/was-scanner:latest
          docker run --rm \
            --link juice-shop:juice-shop \
            -v $(pwd):/scanner \
            -e WAS_MODE=cicd \
            -e ACCESS_KEY=${ACCESS_KEY} \
            -e SECRET_KEY=${SECRET_KEY} \
            tenable/was-scanner:latest

      - name: Cleanup
        if: always()
        run: docker stop juice-shop || true
