name: CI WAS Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tenablescan:
    name: was-cicd
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Create Docker network
        run: docker network create juice-shop-net

      - name: Start Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm --name juice-shop --network juice-shop-net -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!";
              exit 0;
            fi
            echo "Waiting for Juice Shop...";
            sleep 5
          done
          echo "Juice Shop failed to start";
          exit 1

      - name: Run WAS
        run: |
          docker pull tenable/was-scanner:latest
          docker run \
            --network juice-shop-net \
            -e WAS_MODE=cicd \
            -e PLATFORM_URL=https://sensor.cloud.tenable.com \
            -e ACCESS_KEY=$ACCESS_KEY \
            -e SECRET_KEY=$SECRET_KEY \
            -v ${{ github.workspace }}:/scanner \
            tenable/was-scanner:latest
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Cleanup containers
        run: |
          docker stop juice-shop || true
          docker network rm juice-shop-net || true
