name: Tenable WAS CI Scan
on: [push, pull_request]
jobs:
  tenable-was-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create network
        run: docker network create juice-shop-net

      - name: Start OWASP Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm \
            --name juice-shop \
            --network juice-shop-net \
            -p 3000:3000 \
            bkimminich/juice-shop

      - name: Wait for Juice Shop (host port)
        run: |
          for i in {1..12}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              exit 0
            fi
            echo "Waiting… ($i)"
            sleep 5
          done
          echo "Timed out." >&2
          exit 1

      - name: Ensure tenable_was.conf is correct
        run: |
          head -n 20 tenable_was.conf

      - name: Run Tenable WAS Scanner
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker pull tenable/was-scanner:latest
          docker run --rm \
            --network juice-shop-net \
            --ipc=host \
            --security-opt seccomp=unconfined \
            --cap-add SYS_ADMIN \
            -v $(pwd):/scanner \
            -e WAS_MODE=cicd \
            -e ACCESS_KEY=${ACCESS_KEY} \
            -e SECRET_KEY=${SECRET_KEY} \
            tenable/was-scanner:latest
          
          echo "=== scanner.log ==="
          cat scanner.log || echo "(no scanner.log found)"

      - name: Cleanup
        if: always()
        run: docker stop juice-shop || true
