name: Tenable WAS CI Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tenable-was-scan:
    name: Run Tenable WAS Docker CI/CD Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start network
        run: docker network create juice-shop-net

      - name: Start OWASP Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm \
            --name juice-shop \
            --network juice-shop-net \
            -p 3000:3000 \
            bkimminich/juice-shop
          
      - name: Wait for Juice Shop (in‐network)
        run: |
          for i in {1..12}; do
            if docker run --rm --network juice-shop-net curlimages/curl \
                 curl -s http://juice-shop:3000 > /dev/null; then
              echo "Juice Shop is up inside the network!"
              exit 0
            fi
            echo "Waiting for Juice Shop in‐network… ($i)"
            sleep 5
          done
          echo "Timed out waiting for Juice Shop in‐network"
          exit 1

      - name: Run Tenable Web App Scanner
        run: |
          docker pull tenable/was-scanner:latest
          docker run \
            --network juice-shop-net \
            -v $(pwd):/scanner \
            -t \
            -e WAS_MODE=cicd \
            -e ACCESS_KEY=${ACCESS_KEY} \
            -e SECRET_KEY=${SECRET_KEY} \
            tenable/was-scanner
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Cleanup
        if: always()
        run: docker stop juice-shop || true
