name: Tenable WAS CI Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tenable-was-scan:
    name: Run Tenable WAS Docker CI/CD Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start OWASP Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm \
            --name juice-shop \
            -p 3000:3000 \
            bkimminich/juice-shop

      - name: Run Tenable Web App Scanner
        run: |
          docker pull tenable/was-scanner:latest
          docker run -v $(pwd):/scanner -t -e WAS_MODE=cicd -e ACCESS_KEY=${ACCESS_KEY} -e SECRET_KEY=${SECRET_KEY} --link juice-shop:juice-shop
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Cleanup
        if: always()
        run: docker stop juice-shop || true
